permalink: /:category/:title.html
url: http://www.f2es.net
paginate: 5 

catalog :
    category:
        css: CSS
        javascript: JavaScript
        jquery: jQuery
        html: HTML
        performance: 优化
        links: LINKS
    categories:
      - name: css
        title: CSS

      - name: javascript
        title: JavaScript

      - name: jquery
        title: jQuery

      - name: html
        title: HTML

      - name: performance
        title: 优化

      - name: links
        title: LINKS